//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using Dpws.Client;
using Dpws.Client.Discovery;
using Dpws.Client.Eventing;
using Ws.Services;
using Ws.Services.Utilities;
using Ws.Services.Binding;
using Ws.Services.Soap;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;

namespace tempuri.org
{
    
    
    public class IService1ClientProxy : DpwsClient
    {
        
        private IRequestChannel m_requestChannel = null;
        
        public IService1ClientProxy(Binding binding, ProtocolVersion version) : 
                base(binding, version)
        {

            // Set client endpoint address
            m_requestChannel = m_localBinding.CreateClientChannel(new ClientBindingContext(m_version));
        }
        
        public virtual getServerAddressWithPortResponse getServerAddressWithPort(getServerAddressWithPort req)
        {

            // Create request header
            String action;
            action = "http://tempuri.org/IService1/getServerAddressWithPort";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            getServerAddressWithPortDataContractSerializer reqDcs;
            reqDcs = new getServerAddressWithPortDataContractSerializer("getServerAddressWithPort", "http://tempuri.org/");
            request.Serializer = reqDcs;
            request.Method = "getServerAddressWithPort";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            getServerAddressWithPortResponseDataContractSerializer respDcs;
            respDcs = new getServerAddressWithPortResponseDataContractSerializer("getServerAddressWithPortResponse", "http://tempuri.org/");
            getServerAddressWithPortResponse resp;
            resp = ((getServerAddressWithPortResponse)(respDcs.ReadObject(response.Reader)));
            response.Reader.Dispose();
            response.Reader = null;
            return resp;
        }
        
        public virtual keepAliveResponse keepAlive(keepAlive req)
        {

            // Create request header
            String action;
            action = "http://tempuri.org/IService1/keepAlive";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            keepAliveDataContractSerializer reqDcs;
            reqDcs = new keepAliveDataContractSerializer("keepAlive", "http://tempuri.org/");
            request.Serializer = reqDcs;
            request.Method = "keepAlive";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            keepAliveResponseDataContractSerializer respDcs;
            respDcs = new keepAliveResponseDataContractSerializer("keepAliveResponse", "http://tempuri.org/");
            keepAliveResponse resp;
            resp = ((keepAliveResponse)(respDcs.ReadObject(response.Reader)));
            response.Reader.Dispose();
            response.Reader = null;
            return resp;
        }
        
        public virtual isValidResponse isValid(isValid req)
        {

            // Create request header
            String action;
            action = "http://tempuri.org/IService1/isValid";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            isValidDataContractSerializer reqDcs;
            reqDcs = new isValidDataContractSerializer("isValid", "http://tempuri.org/");
            request.Serializer = reqDcs;
            request.Method = "isValid";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            isValidResponseDataContractSerializer respDcs;
            respDcs = new isValidResponseDataContractSerializer("isValidResponse", "http://tempuri.org/");
            isValidResponse resp;
            resp = ((isValidResponse)(respDcs.ReadObject(response.Reader)));
            response.Reader.Dispose();
            response.Reader = null;
            return resp;
        }
    }
}
